Make test failure messages/tracebacks unique to PSM Interop (#21)
This PR:
- Make test failure messages/tracebacks unique to PSM Interop to allow
for easier grepping/matchers (more details below.
- Replaces `self.id()` calls in the framework logs with custom
`self.test_name`. For example,
`--- Starting subTest __main__.AppNetTest.test_ping_pong.0_create_health_check ---`
  becomes
`--- Starting subTest AppNetTest.test_ping_pong.0_create_health_check ---`.
- Changes the log level of `----- TestCase ... FAILED -----` message
from `info` to `error`.
- Adds `FakeTest` to make future work on the log messages easier 
 
The new error format:
```
E0118 09:59:38.289015 140704433060736 base_testcase.py:39] ----- PSM Test Case FAILED: ClassName.test_method -----
E0118 09:59:38.289084 140704433060736 base_testcase.py:87] ($failure_type) PSM Interop Test Failed: ClassName.test_method
^^^^^
[ClassName.test_method] PSM Failed Test Traceback BEGIN
Traceback (most recent call last):
...
AssertionError: description
[ClassName.test_method] PSM Failed Test Traceback END
```

This format will allow us to drastically simplify buggrep matchers that
search within the stack traces of _our_ framework, which also resulted
in a test failure (e.g. didn't recover after retrying).
Now we can do a plain-text grep for `PSM Failed Test Traceback BEGIN`
instead of an extended regex grep for `E[0-9]{4}.*base_testcase.*ERROR
Traceback in`.
Text `PSM Failed Test Traceback BEGIN` is guaranteed to be only produced
on test failure. Additionally, this allows to restrict matchers to a
specific test in the same swoop, just do a plain-text search for
`[TestClass.test_method] PSM Failed Test Traceback BEGIN`.

Initial PR that added the traceback: grpc/grpc#34023.