Add try catch in docker.py to avoid leaking in case of error (#239)
Added try catch to avoid resource leak when we have exception, this
cause subsequent test also fail

Example : b/495344114
test_fallback_mid_startup has this exception
```
   Traceback (most recent call last):
      File "/tmp/tmp.jfDdTcsnMA/psm-interop/tests/fallback_test.py", line 247, in
      test_fallback_mid_startup
        with (
      File "/tmp/tmp.jfDdTcsnMA/psm-interop/framework/helpers/docker.py", line 236, in
      __enter__
        self.update_resources(self.initial_resources)
      File "/tmp/tmp.jfDdTcsnMA/psm-interop/framework/helpers/docker.py", line 250, in
      update_resources
        return stub.SetResources(resources)
      # ...
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
       status = StatusCode.UNAVAILABLE
       details = "failed to connect to all addresses; last error: UNAVAILABLE:
      ipv4:127.0.0.1:56553: recvmsg:Connection reset by peer"
```

This caused next test to fail
test_fallback_mid_update:
```
   docker.errors.APIError: 500 Server Error ...
   Internal Server Error ("failed to set up container networking ...
   Bind for 0.0.0.0:56553 failed: port is already allocated")
```